fix: Unable to disable page view on POST page
hugo-next/hugo-theme-next pull request #84
Opened 2023-01-09 01:51 UTC by yolee599

Issue #83

2023-01-09 08:51 UTC, elkan1788 requested changes
请检查下冲突部分的代码，需要调整。

2023-01-09 08:51 UTC, elkan1788 commented on layouts/_default/terms.html
> +            <a class="category-list-link" href="{{ "/categories/" | relLangURL }}{{ $name | urlize  }}" data-pjax-state="">{{ .Page.Title }}</a>
这段代码冲突了，这里的`$name`变量最后是要进行小写，避免访问出现404。

2023-01-09 08:51 UTC, elkan1788 commented on layouts/_default/terms.html
> +        <a class="tag-cloud-{{ index (shuffle $randNums) 0 }}" href="{{ "/tags/" | relLangURL }}{{ $name | urlize  }}">{{ .Page.Title }}
同上

2023-01-10 01:49 UTC, yolee599 commented
The develop branch is behind the main branch, so change to hotfix.

2023-01-18 11:02 UTC, elkan1788 commented
> The develop branch is behind the main branch, so change to hotfix.

Sorry, it's not a hotfix apply, recommand to change your code to develop branch, thanks.

2023-01-27 09:03 UTC, closed without merging